version: '3.7'

services:

  sample:
    container_name: contador
    image: node:16.15.1-alpine
    working_dir: /app
    command: >
          sh -c  "npm install &&
          npm run dev"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000